image: Visual Studio 2015
clone_folder: c:\projects\worktree\libalmath
configuration: Release

# variable definitions
# variables will be accessible as %myvar% from batch,
# and as $env:myvar from powershell
# Here some doc:
# - https://kevinmarquette.github.io/2017-01-13-powershell-variable-substitution-in-strings
# - https://msdn.microsoft.com/powershell/reference/5.1/Microsoft.PowerShell.Core/about/about_Functions
environment:
  maya_libs_archive_path: '%APPVEYOR_BUILD_FOLDER%\deps\mayasdk\maya2017-libs-win64.zip'
  maya_headers_archive_path: '%APPVEYOR_BUILD_FOLDER%\deps\mayasdk\maya2017-headers-win64.zip'
  qitoolchain_feed_url: 'file:///%APPVEYOR_BUILD_FOLDER%/deps/toolchains/feeds/win64-vs2015.xml'
  MAYA_LOCATION: C:\Users\appveyor\Maya2017

install:
# extract the Maya libs in MAYA_LOCATION
# extract the C++ headers in MAYA_LOCATION\include, as recommanded in
# http://help.autodesk.com/view/MAYAUL/2017/ENU/?guid=__files_Setting_up_your_build_env_Windows_env_32bit_and_64bit_htm
- ps: |
    $dir = Split-Path -Path $env:MAYA_LOCATION
    Push-Location $dir
    & 7z x $env:maya_libs_archive_path
    & 7z x $env:maya_headers_archive_path
    Pop-Location
    if (-Not (Test-Path $env:MAYA_LOCATION)) {
        throw "failed to prepare MAYA_LOCATION"
    }

before_build:
# cfr https://www.appveyor.com/docs/lang/cpp/
- call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64
- call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64
- set PATH=C:\Python27\scripts;%PATH%
- git submodule update --init --recursive
- pip install ./deps/qibuild
# create and populate the toolchain
- ps: |
    $tc = "master-host"
    & qitoolchain create $tc ${env:qitoolchain_feed_url}
    & qitoolchain info $tc
    & qibuild add-config host -t $tc
# setup a worktree
# we create worktree.xml, just like qisrc init would have done
#
# I failed to create xml content with batch echo, because of weird escaping
# of angle brackets, so I resorted to powershell
# configure!
- qibuild configure -c host -G "Visual Studio 14 2015 Win64" --release -DALMATH_WITH_QIGEOMETRY=OFF -DALMATH_WITH_MAYAPLUGIN=ON -DWITH_PYTHON=OFF -DALMATH_AS_STATIC_LIBRARY=ON -DMAYA_INCLUDE_DIRS="%MAYA_LOCATION%/include" -DMAYA_INSTALL_BASE_PATH="C:\Users\appveyor"

build_script:
- qibuild make -c host

test_script:
# skip the mayaplugin test, because it crashes
# TODO: understand why
- qitest run -c host -k .*almath.*
#- qitest run -c host

artifacts:
- path: '**\*.mll'
